#ifndef __REGISTERLIST_H
#define	__REGISTERLIST_H

#include "define.h"
#include "ud_str.h"
#include "bacnet.h"

typedef enum
{
	EEP_SERIALNUMBER_LOWORD = 0,
	EEP_SERIALNUMBER_HIWORD = EEP_SERIALNUMBER_LOWORD + 2,
	EEP_VERSION_NUMBER_LO = EEP_SERIALNUMBER_HIWORD + 2,
	EEP_VERSION_NUMBER_HI,
	EEP_ADDRESS,
	EEP_PRODUCT_MODEL,
	EEP_HARDWARE_REV,
	EEP_PIC_VER,
	EEP_BASE_ADDRESS,

	EEP_UPDATE_STATUS = 16,
	EEP_SERIALNUMBER_WRITE_FLAG,
	EEP_MODBUS_COM_CONFIG = 20 , 
	
	EEP_BAUDRATE ,
	EEP_INSTANCE_1 ,
	EEP_INSTANCE_2 ,
	EEP_INSTANCE_3 ,
	EEP_INSTANCE_4 ,
	
	
	EEP_INSTANCE_LOWORD = 35,
	EEP_INSTANCE_HIWORD = 37,
	EEP_STATION_NUMBER = 39, 
	
	EEP_MAC_ADDRESS_1 = 40,
	EEP_MAC_ADDRESS_2,
	EEP_MAC_ADDRESS_3,
	EEP_MAC_ADDRESS_4,
	EEP_MAC_ADDRESS_5,
	EEP_MAC_ADDRESS_6,	
	EEP_IP_MODE		,
	EEP_IP_ADDRESS_1,
	EEP_IP_ADDRESS_2 ,
	EEP_IP_ADDRESS_3 ,
	EEP_IP_ADDRESS_4 ,
	EEP_SUB_MASK_ADDRESS_1 ,
	EEP_SUB_MASK_ADDRESS_2 ,
	EEP_SUB_MASK_ADDRESS_3 ,
	EEP_SUB_MASK_ADDRESS_4 ,
	EEP_GATEWAY_ADDRESS_1 ,
	EEP_GATEWAY_ADDRESS_2 ,
	EEP_GATEWAY_ADDRESS_3 ,
	EEP_GATEWAY_ADDRESS_4 ,
	EEP_TCP_SERVER ,
	EEP_LISTEN_PORT_HI	,
	EEP_LISTEN_PORT_LO ,
//phrase a
	EEP_VRMS_CAL0_VALUE_BYTE_0,
	EEP_VRMS_CAL0_VALUE_BYTE_1,
	EEP_VRMS_CAL0_ADC_BYTE_0,
	EEP_VRMS_CAL0_ADC_BYTE_1,
	EEP_VRMS_CAL0_ADC_BYTE_2,
	EEP_VRMS_CAL0_ADC_BYTE_3,
	EEP_VRMS_CAL0_SLOPE_BYTE_0,
	EEP_VRMS_CAL0_SLOPE_BYTE_1,
	EEP_VRMS_CAL0_SLOPE_BYTE_2,
	EEP_VRMS_CAL0_SLOPE_BYTE_3,
	
	EEP_IRMS_CAL0_VALUE_BYTE_0,
	EEP_IRMS_CAL0_VALUE_BYTE_1,
	EEP_IRMS_CAL0_ADC_BYTE_0,
	EEP_IRMS_CAL0_ADC_BYTE_1,
	EEP_IRMS_CAL0_ADC_BYTE_2,
	EEP_IRMS_CAL0_ADC_BYTE_3,
	EEP_IRMS_CAL0_SLOPE_BYTE_0,
	EEP_IRMS_CAL0_SLOPE_BYTE_1,
	EEP_IRMS_CAL0_SLOPE_BYTE_2,
	EEP_IRMS_CAL0_SLOPE_BYTE_3,
	
	
	//phrase b
	
	EEP_VRMS_CAL1_VALUE_BYTE_0,
	EEP_VRMS_CAL1_VALUE_BYTE_1,
	EEP_VRMS_CAL1_ADC_BYTE_0,
	EEP_VRMS_CAL1_ADC_BYTE_1,
	EEP_VRMS_CAL1_ADC_BYTE_2,
	EEP_VRMS_CAL1_ADC_BYTE_3,
	EEP_VRMS_CAL1_SLOPE_BYTE_0,
	EEP_VRMS_CAL1_SLOPE_BYTE_1,
	EEP_VRMS_CAL1_SLOPE_BYTE_2,
	EEP_VRMS_CAL1_SLOPE_BYTE_3,
	
	EEP_IRMS_CAL1_VALUE_BYTE_0,
	EEP_IRMS_CAL1_VALUE_BYTE_1,
	EEP_IRMS_CAL1_ADC_BYTE_0,
	EEP_IRMS_CAL1_ADC_BYTE_1,
	EEP_IRMS_CAL1_ADC_BYTE_2,
	EEP_IRMS_CAL1_ADC_BYTE_3,
	EEP_IRMS_CAL1_SLOPE_BYTE_0,
	EEP_IRMS_CAL1_SLOPE_BYTE_1,
	EEP_IRMS_CAL1_SLOPE_BYTE_2,
	EEP_IRMS_CAL1_SLOPE_BYTE_3,
	
	
	
	//phrase c
	EEP_VRMS_CAL2_VALUE_BYTE_0,
	EEP_VRMS_CAL2_VALUE_BYTE_1,
	EEP_VRMS_CAL2_ADC_BYTE_0,
	EEP_VRMS_CAL2_ADC_BYTE_1,
	EEP_VRMS_CAL2_ADC_BYTE_2,
	EEP_VRMS_CAL2_ADC_BYTE_3,
	EEP_VRMS_CAL2_SLOPE_BYTE_0,
	EEP_VRMS_CAL2_SLOPE_BYTE_1,
	EEP_VRMS_CAL2_SLOPE_BYTE_2,
	EEP_VRMS_CAL2_SLOPE_BYTE_3,
	
	EEP_IRMS_CAL2_VALUE_BYTE_0,
	EEP_IRMS_CAL2_VALUE_BYTE_1,
	EEP_IRMS_CAL2_ADC_BYTE_0,
	EEP_IRMS_CAL2_ADC_BYTE_1,
	EEP_IRMS_CAL2_ADC_BYTE_2,
	EEP_IRMS_CAL2_ADC_BYTE_3,
	EEP_IRMS_CAL2_SLOPE_BYTE_0,
	EEP_IRMS_CAL2_SLOPE_BYTE_1,
	EEP_IRMS_CAL2_SLOPE_BYTE_2,
	EEP_IRMS_CAL2_SLOPE_BYTE_3,


	EEP_TSTAT_NAME1, 
	EEP_TSTAT_NAME2 = EEP_TSTAT_NAME1 + 2, 
	EEP_TSTAT_NAME3 = EEP_TSTAT_NAME2 + 2, 
	EEP_TSTAT_NAME4 = EEP_TSTAT_NAME3 + 2, 
	EEP_TSTAT_NAME5 = EEP_TSTAT_NAME4 + 2, 
	EEP_TSTAT_NAME6 = EEP_TSTAT_NAME5 + 2, 
	EEP_TSTAT_NAME7 = EEP_TSTAT_NAME6 + 2, 
	EEP_TSTAT_NAME8 = EEP_TSTAT_NAME7 + 2, 
	EEP_TSTAT_NAME9 = EEP_TSTAT_NAME8 + 2, 
	EEP_TSTAT_NAME10 = EEP_TSTAT_NAME9 + 2, 
	EEP_NAME_END = EEP_TSTAT_NAME10 + 2,
	
	
} EEP_MAP;

typedef enum
{
	MODBUS_SERIALNUMBER_LOWORD = 0,             
	MODBUS_SERIALNUMBER_HIWORD = 2,
	MODBUS_VERSION_NUMBER_LO = 4,
	MODBUS_VERSION_NUMBER_HI = 5,
	MODBUS_ADDRESS = 6,
	MODBUS_PRODUCT_MODEL,
	MODBUS_HARDWARE_REV,
	//MODBUS_PIC_VERSION,
	MODBUS_ADDRESS_PLUG_N_PLAY,
	MODBUS_BAUDRATE = 15,			// base address select
	MODBUS_UPDATE_STATUS = 16,			// status for update flash
	
	MODBUS_PROTOCOL_TYPE = 21,
	
	MODBUS_INSTANCE_LOWORD = 37,	
	MODBUS_INSTANCE_HIWORD = 38,
	MODBUS_STATION_NUMBER = 39, 
	
	MODBUS_MAC_ADDRESS_1	= 40,
	MODBUS_MAC_ADDRESS_2,
	MODBUS_MAC_ADDRESS_3,
	MODBUS_MAC_ADDRESS_4,
	MODBUS_MAC_ADDRESS_5,
	MODBUS_MAC_ADDRESS_6,	
	MODBUS_IP_MODE		= 46,
	MODBUS_IP_ADDRESS_1	= 47,
	MODBUS_IP_ADDRESS_2 = 48,
	MODBUS_IP_ADDRESS_3 = 49,
	MODBUS_IP_ADDRESS_4 = 50,
	
	MODBUS_SUB_MASK_ADDRESS_1 = 51,
	MODBUS_SUB_MASK_ADDRESS_2 = 52,
	MODBUS_SUB_MASK_ADDRESS_3 = 53,
	MODBUS_SUB_MASK_ADDRESS_4 = 54,
	
	MODBUS_GATEWAY_ADDRESS_1 = 55,
	MODBUS_GATEWAY_ADDRESS_2 = 56,
	MODBUS_GATEWAY_ADDRESS_3 = 57,
	MODBUS_GATEWAY_ADDRESS_4 = 58,
	
	MODBUS_TCP_SERVER   = 59,
	MODBUS_LISTEN_PORT	= 60,
	
	
	MODBUS_GHOST_IP_MODE		= 61,
	MODBUS_GHOST_IP_ADDRESS_1	= 62,
	MODBUS_GHOST_IP_ADDRESS_2 = 63,
	MODBUS_GHOST_IP_ADDRESS_3 = 64,
	MODBUS_GHOST_IP_ADDRESS_4 = 65,
	
	MODBUS_GHOST_SUB_MASK_ADDRESS_1 = 66,
	MODBUS_GHOST_SUB_MASK_ADDRESS_2 = 67,
	MODBUS_GHOST_SUB_MASK_ADDRESS_3 = 68,
	MODBUS_GHOST_SUB_MASK_ADDRESS_4 = 69,
	
	MODBUS_GHOST_GATEWAY_ADDRESS_1 = 70,
	MODBUS_GHOST_GATEWAY_ADDRESS_2 = 71,
	MODBUS_GHOST_GATEWAY_ADDRESS_3 = 72,
	MODBUS_GHOST_GATEWAY_ADDRESS_4 = 73,
	
	MODBUS_GHOST_TCP_SERVER   = 74,
	MODBUS_GHOST_LISTEN_PORT	= 75,
	
	MODBUS_WRITE_GHOST_SYSTEM = 76 ,
	MODBUS_MAC_ENABLE		  = 93,
	MODBUS_RESET = 98,	
	MODBUS_SERINALNUMBER_WRITE_FLAG = 99,
	
	// power meter parameter registers start
	//phrase A
	MODBUS_PM0_MODE = 100,
	MODBUS_PM0_ONCHIP_TEMPERATURE,
	MODBUS_PM0_PGA_GAIN,	//?
	MODBUS_PM0_VOLTAGE_FREQUENCY,//103  0.1hz   1
	MODBUS_PM0_PERIOD, //104
	
	MODBUS_PM0_IRQ_ENABLE, //105
	MODBUS_PM0_IRQ_STATUS,//106 

	MODBUS_PM0_VPEAK_HW,//107
	MODBUS_PM0_VPEAK_LW,
	MODBUS_PM0_VRMS_HW,//109
	MODBUS_PM0_VRMS_LW,
	
	MODBUS_PM0_IPEAK_HW,//111
	MODBUS_PM0_IPEAK_LW,
	MODBUS_PM0_IRMS_HW,//113
	MODBUS_PM0_IRMS_LW,
	
	MODBUS_PM0_WAVEFORM_HW,//115
	MODBUS_PM0_WAVEFORM_LW,
	
	MODBUS_PM0_VRMS_VALUE, // 117		//0.1v 	0~300V
	MODBUS_PM0_IRMS_VALUE, // 118		//1A
	
	MODBUS_PM0_VRMS_CAL_VALUE = 120,		// calibrate 0.1 v
	MODBUS_PM0_VRMS_CAL_ADC_HW,
	MODBUS_PM0_VRMS_CAL_ADC_LW,
	MODBUS_PM0_VRMS_CAL_K_HW,
	MODBUS_PM0_VRMS_CAL_K_LW,
	
	MODBUS_PM0_IRMS_CAL_VALUE, // 125
	MODBUS_PM0_IRMS_CAL_ADC_HW,
	MODBUS_PM0_IRMS_CAL_ADC_LW,
	MODBUS_PM0_IRMS_CAL_K_HW,
	MODBUS_PM0_IRMS_CAL_K_LW,
	
	MODBUS_PM0_ACTIVE_POWER,
	MODBUS_PM0_REACTIVE_POWER,
	
	MODBUS_PM0_LINECYC = 137,
	MODBUS_TEST_COUNTER = 138,
	MODBUS_PM_TEST = 139,

// ENERGY CALIBRATION SECTION
	MODBUS_PM0_CF_CAL_EN = 140,
	MODBUS_PM0_CF_IMP_PER_KWH,
	MODBUS_PM0_VT,
	MODBUS_PM0_IT,
	MODBUS_PM0_CF_EXPECTED_HIGH,
	MODBUS_PM0_CF_EXPECTED_LOW,	//145
	MODBUS_PM0_CF_CONST_W_LSB_HIGH,
	MODBUS_PM0_CF_CONST_W_LSB_LOW,
	MODBUS_PM0_LAENERGY_TEST_HIGH,
	MODBUS_PM0_LAENERGY_TEST_LOW,
	
	
	
	MODBUS_PM0_LINECYC_IB,		//150
	
	MODBUS_PM0_OFFSET_CAL_PRO,
	MODBUS_PM0_OFFSET_CALI_EN,
	MODBUS_PM0_I_CORRECTION_HIGH,
	MODBUS_PM0_I_CORRECTION_LOW,
	MODBUS_PM0_LAENERGY_CORRECTION_HIGH,
	MODBUS_PM0_LAENERGY_CORRECTION_LOW,
	MODBUS_PM0_LSB_VARIATION_HIGH,
	MODBUS_PM0_LSB_VARIATION_LOW,
	MODBUS_PM0_LINECYC_I_MIN,

	//phrase B
	MODBUS_PM1_MODE = 200,
	MODBUS_PM1_ONCHIP_TEMPERATURE,
	MODBUS_PM1_PGA_GAIN,	//?
	MODBUS_PM1_VOLTAGE_FREQUENCY,//203  0.1hz   1
	MODBUS_PM1_PERIOD, //204
	
	MODBUS_PM1_IRQ_ENABLE, //205
	MODBUS_PM1_IRQ_STATUS,//206 

	MODBUS_PM1_VPEAK_HW,//207
	MODBUS_PM1_VPEAK_LW,
	MODBUS_PM1_VRMS_HW,//209
	MODBUS_PM1_VRMS_LW,
	
	MODBUS_PM1_IPEAK_HW,//211
	MODBUS_PM1_IPEAK_LW,
	MODBUS_PM1_IRMS_HW,//213
	MODBUS_PM1_IRMS_LW,
	
	MODBUS_PM1_WAVEFORM_HW,//215
	MODBUS_PM1_WAVEFORM_LW,
	
	MODBUS_PM1_VRMS_VALUE, // 217		//0.1v 	0~300V
	MODBUS_PM1_IRMS_VALUE, // 218		//1A
	
	MODBUS_PM1_VRMS_CAL_VALUE = 220,		// calibrate 0.1 v
	MODBUS_PM1_VRMS_CAL_ADC_HW,
	MODBUS_PM1_VRMS_CAL_ADC_LW,
	MODBUS_PM1_VRMS_CAL_K_HW,
	MODBUS_PM1_VRMS_CAL_K_LW,
	
	MODBUS_PM1_IRMS_CAL_VALUE, // 225
	MODBUS_PM1_IRMS_CAL_ADC_HW,
	MODBUS_PM1_IRMS_CAL_ADC_LW,
	MODBUS_PM1_IRMS_CAL_K_HW,
	MODBUS_PM1_IRMS_CAL_K_LW,
	
	MODBUS_PM1_ACTIVE_POWER,
	MODBUS_PM1_REACTIVE_POWER,
	
	MODBUS_PM1_LINECYC = 237, 

// ENERGY CALIBRATION SECTION
	MODBUS_PM1_CF_CAL_EN = 240,
	MODBUS_PM1_CF_IMP_PER_KWH,
	MODBUS_PM1_VT,
	MODBUS_PM1_IT,
	MODBUS_PM1_CF_EXPECTED_HIGH,
	MODBUS_PM1_CF_EXPECTED_LOW,	//245
	MODBUS_PM1_CF_CONST_W_LSB_HIGH,
	MODBUS_PM1_CF_CONST_W_LSB_LOW,
	MODBUS_PM1_LAENERGY_TEST_HIGH,
	MODBUS_PM1_LAENERGY_TEST_LOW,
	
	
	
	MODBUS_PM1_LINECYC_IB,		//250
	
	MODBUS_PM1_OFFSET_CAL_PRO,
	MODBUS_PM1_OFFSET_CALI_EN,
	MODBUS_PM1_I_CORRECTION_HIGH,
	MODBUS_PM1_I_CORRECTION_LOW,
	MODBUS_PM1_LAENERGY_CORRECTION_HIGH,
	MODBUS_PM1_LAENERGY_CORRECTION_LOW,
	MODBUS_PM1_LSB_VARIATION_HIGH,
	MODBUS_PM1_LSB_VARIATION_LOW,
	MODBUS_PM1_LINECYC_I_MIN,


	//phrase c
	MODBUS_PM2_MODE = 300,
	MODBUS_PM2_ONCHIP_TEMPERATURE,
	MODBUS_PM2_PGA_GAIN,	//?
	MODBUS_PM2_VOLTAGE_FREQUENCY,//303  0.1hz   1
	MODBUS_PM2_PERIOD, //304
	
	MODBUS_PM2_IRQ_ENABLE, //305
	MODBUS_PM2_IRQ_STATUS,//306 

	MODBUS_PM2_VPEAK_HW,//307
	MODBUS_PM2_VPEAK_LW,
	MODBUS_PM2_VRMS_HW,//309
	MODBUS_PM2_VRMS_LW,
	
	MODBUS_PM2_IPEAK_HW,//311
	MODBUS_PM2_IPEAK_LW,
	MODBUS_PM2_IRMS_HW,//313
	MODBUS_PM2_IRMS_LW,
	
	MODBUS_PM2_WAVEFORM_HW,//315
	MODBUS_PM2_WAVEFORM_LW,
	
	MODBUS_PM2_VRMS_VALUE, // 317		//0.1v 	0~300V
	MODBUS_PM2_IRMS_VALUE, // 318		//1A
	
	MODBUS_PM2_VRMS_CAL_VALUE = 320,		// calibrate 0.1 v
	MODBUS_PM2_VRMS_CAL_ADC_HW,
	MODBUS_PM2_VRMS_CAL_ADC_LW,
	MODBUS_PM2_VRMS_CAL_K_HW,
	MODBUS_PM2_VRMS_CAL_K_LW,
	
	MODBUS_PM2_IRMS_CAL_VALUE, // 325
	MODBUS_PM2_IRMS_CAL_ADC_HW,
	MODBUS_PM2_IRMS_CAL_ADC_LW,
	MODBUS_PM2_IRMS_CAL_K_HW,
	MODBUS_PM2_IRMS_CAL_K_LW,
	
	MODBUS_PM2_ACTIVE_POWER,
	MODBUS_PM2_REACTIVE_POWER,
	
	MODBUS_PM2_LINECYC = 337, 

// ENERGY CALIBRATION SECTION
	MODBUS_PM2_CF_CAL_EN = 340,
	MODBUS_PM2_CF_IMP_PER_KWH,
	MODBUS_PM2_VT,
	MODBUS_PM2_IT,
	MODBUS_PM2_CF_EXPECTED_HIGH,
	MODBUS_PM2_CF_EXPECTED_LOW,	//345
	MODBUS_PM2_CF_CONST_W_LSB_HIGH,
	MODBUS_PM2_CF_CONST_W_LSB_LOW,
	MODBUS_PM2_LAENERGY_TEST_HIGH,
	MODBUS_PM2_LAENERGY_TEST_LOW,
	
	
	
	MODBUS_PM2_LINECYC_IB,		//350
	
	MODBUS_PM2_OFFSET_CAL_PRO,
	MODBUS_PM2_OFFSET_CALI_EN,
	MODBUS_PM2_I_CORRECTION_HIGH,
	MODBUS_PM2_I_CORRECTION_LOW,
	MODBUS_PM2_LAENERGY_CORRECTION_HIGH,
	MODBUS_PM2_LAENERGY_CORRECTION_LOW,
	MODBUS_PM2_LSB_VARIATION_HIGH,
	MODBUS_PM2_LSB_VARIATION_LOW,
	MODBUS_PM2_LINECYC_I_MIN,








	MODBUS_AI_VALUE0 = 1000,
	MODBUS_AI_VALUE1,
	MODBUS_AI_VALUE2,
	MODBUS_AI_VALUE3,
	
	MODBUS_AI_FILTER0 = 1005,
	MODBUS_AI_FILTER1,
	MODBUS_AI_FILTER2,
	MODBUS_AI_FILTER3, 

	
	MODBUS_AI_RANGE0 = 1010,
	MODBUS_AI_RANGE1,
	MODBUS_AI_RANGE2,
	MODBUS_AI_RANGE3, 
	
	MODBUS_AI_AM0 = 1015,
	MODBUS_AI_AM1,
	MODBUS_AI_AM2,
	MODBUS_AI_AM3,
	 
	MODBUS_AI_CAL_SIGN0 = 1020,
	MODBUS_AI_CAL_SIGN1,
	MODBUS_AI_CAL_SIGN2,
	MODBUS_AI_CAL_SIGN3,
	
	MODBUS_AI_OFFSET0 = 1025,
	MODBUS_AI_OFFSET1,
	MODBUS_AI_OFFSET2,
	MODBUS_AI_OFFSET3,
	
	MODBUS_AO_VALUE0 = 1030,
	MODBUS_AO_VALUE1,
	MODBUS_AO_VALUE2,
	MODBUS_AO_VALUE3,
	
	MODBUS_AO_RANGE0 = 1035,
	MODBUS_AO_RANGE1,
	MODBUS_AO_RANGE2,
	MODBUS_AO_RANGE3,
	
	MODBUS_AO_AM0 = 1040,
	MODBUS_AO_AM1,
	MODBUS_AO_AM2,
	MODBUS_AO_AM3,
	
	MODBUS_AI_RAW0 = 1045,
	MODBUS_AI_RAW1,
	MODBUS_AI_RAW2,
	MODBUS_AI_RAW3,
	
	MODBUS_AO_RAW0 = 1050,
	MODBUS_AO_RAW1,
	MODBUS_AO_RAW2,
	MODBUS_AO_RAW3,
	
	
	
	
	
	
	
	TSTAT_NAME_ENABLE = 714,//default value = 0x55 indicate tstat name function is present
	TSTAT_NAME1,
	TSTAT_NAME2,
	TSTAT_NAME3,
	TSTAT_NAME4,
	TSTAT_NAME5,
	TSTAT_NAME6,
	TSTAT_NAME7,
	TSTAT_NAME8,
	TSTAT_NAME9,
	TSTAT_NAME10,  
	
	MODBUS_Energy_Real_Total  = 1000, 
	MODBUS_Energy_Reactive_Total, 
	MODBUS_Energy_Apparent,
	MODBUS_True_Power_Factor_Total,
	MODBUS_Current_Phase_A,
	MODBUS_Current_Phase_B,
	MODBUS_Current_Phase_C,
	MODBUS_Current_Neutral,
	MODBUS_Current_Ground,
	MODBUS_Current_3_Phase_Average,
	MODBUS_Voltage_A_B,
	MODBUS_Voltage_B_C,
	MODBUS_Voltage_C_A,
	MODBUS_Voltage_L_L_Average,
	MODBUS_Voltage_A_N,
	MODBUS_Voltage_B_N,
	MODBUS_Voltage_C_N,
	MODBUS_Voltage_N_G,
	MODBUS_Voltage_L_N_Average,
	MODBUS_Real_Power_Phase_A,
	MODBUS_Real_Power_Phase_B,
	MODBUS_Real_Power_Phase_C,
	MODBUS_Real_Power_Total,
	MODBUS_Reactive_Power_Phase_A,
	MODBUS_Reactive_Power_Phase_B,
	MODBUS_Reactive_Power_Phase_C,
	MODBUS_Reactive_Power_Total,
	MODBUS_Apparent_Power_Phase_A,
	MODBUS_Apparent_Power_Phase_B,
	MODBUS_Apparent_Power_Phase_C,
	MODBUS_Apparent_Power_Total,
	MODBUS_True_Power_Factor_Phase_A,
	MODBUS_True_Power_Factor_Phase_B,
	MODBUS_True_Power_Factor_Phase_C, 
	MODBUS_Frequency,
	MODBUS_Energy_Real_In,
	MODBUS_Energy_Reactive_In,
	MODBUS_Energy_Real_Out,
	MODBUS_Energy_Reactive_Out,
 
	MODBUS_Energy_Conditional_Real_In,
	MODBUS_Energy_Conditional_Reactive_In,
	MODBUS_Energy_Conditional_Real_Out,
	MODBUS_Energy_Conditional_Reactive_Out,
	MODBUS_Energy_Conditional_Apparent,
	MODBUS_Energy_Incremental_Real_In_Last_Complete_Interval,
	MODBUS_Energy_Incremental_Reactive_In_Last_Complete_Interval,
	MODBUS_Energy_Incremental_Real_Out_Last_Complete_Interval,
	MODBUS_Energy_Incremental_Reactive_Out_Last_Complete_Interval,
	MODBUS_Energy_Incremental_Apparent_Last_Complete_Interval,
	MODBUS_Energy_Incremental_Real_In_Present_interval,
	MODBUS_Energy_Incremental_Reactive_In_Present_Interval,
	MODBUS_Energy_Incremental_Real_Out_Present_Interval,
	MODBUS_Energy_Incremental_Reactive_Out_Present_Interval,
	MODBUS_Energy_Incremental_Apparent_Present_Interval, 
	MODBUS_Energy_Reactive_Quadrant_1,
	MODBUS_Energy_Reactive_Quadrant_2,
	MODBUS_Energy_Reactive_Quadrant_3,
	MODBUS_Energy_Reactive_Quadrant_4,
	MODBUS_Cumulative_Usage_Input_Channel_1,
	MODBUS_Cumulative_Usage_Input_Channel_2,
	MODBUS_Cumulative_Usage_Input_Channel_3,
	MODBUS_Cumulative_Usage_Input_Channel_4,
	MODBUS_Cumulative_Usage_Input_Channel_5,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Today,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Yesterday,
	MODBUS_Energy_Real_3_Phase_Total_Usage_This_Week,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Last_Week,
	MODBUS_Energy_Real_3_Phase_Total_Usage_This_Month,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Last_Month,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Today,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Yesterday,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_This_Week,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Last_Week,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_This_Month,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Last_Month, 
	MODBUS_Energy_Real_3_Phase_Total_Usage_First_Shift_Today,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Second_Shift_Today,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Third_Shift_Today,
	MODBUS_Energy_Real_3_Phase_Total_Usage_First_Shift_Yesterday,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Second_Shift_Yesterday,
	MDOBUS_Energy_Real_3_Phase_Total_Energy_Real_3_Phase_Total,
	MODUBS_Energy_Real_3_Phase_Total_Usage_First_Shift_This_Week,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Second_Shift_This_Week,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Third_Shift_This_Week,
	MODUBS_Energy_Real_3_Phase_Total_Usage_First_Shift_Last_Week,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Second_Shift_Last_Week,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Third_Shift_Last_Week,
	MODBUS_Energy_Real_3_Phase_Total_Usage_First_Shift_This_Month,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Second_Shift_This_Month,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Third_Shift_This_Month,
	MODBUS_Energy_Real_3_Phase_Total_Usage_First_Shift_Last_Month,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Second_Shift_Last_Month,
	MODBUS_Energy_Real_3_Phase_Total_Usage_Third_Shift_Last_Month,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_First_Shift_Today,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Second_Shift_Today,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Third_Shift_Today,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_First_Shift_Yesterday,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Second_Shift_Yesterday,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Third_Shift_Yesterday,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_First_Shift_This_Week,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Second_Shift_This_Week,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Third_Shift_This_Week,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_First_Shift_Last_Week,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Second_Shift_Last_Week,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Third_Shift_Last_Week,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_First_Shift_This_Month,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Second_Shift_This_Month,
	MODBUS_Energy_Apparent_3_Phase_Total_Energy_Apparent_3_Phase_Total,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_First_Shift_Last_Month,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Second_Shift_Last_Month,
	MODBUS_Energy_Apparent_3_Phase_Total_Usage_Third_Shift_Last_Month, 
	 
	MODBUS_USER_BLOCK_FIRST = 9999 ,
	 
	MODBUS_OUTPUT_BLOCK_FIRST = 10000,      
	MODBUS_OUTPUT_BLOCK_LAST  = MODBUS_OUTPUT_BLOCK_FIRST + MAX_OUTS * ((sizeof(Str_out_point) + 1)/ 2) - 1,
	
	MODBUS_INPUT_BLOCK_FIRST  =  MODBUS_OUTPUT_BLOCK_FIRST + 64 * ((sizeof(Str_out_point) + 1)/ 2),
	MODBUS_INPUT_BLOCK_LAST   = MODBUS_INPUT_BLOCK_FIRST + MAX_INS * ((sizeof(Str_in_point) + 1) / 2) - 1,

	MODBUS_VAR_BLOCK_FIRST    = MODBUS_INPUT_BLOCK_FIRST + 64 * ((sizeof(Str_in_point) + 1) / 2),
	MODBUS_VAR_BLOCK_LAST     = MODBUS_VAR_BLOCK_FIRST + MAX_AVS * ((sizeof(Str_variable_point) + 1) / 2) - 1,
	
//	MODBUS_PRG_BLOCK_FIRST    = MODBUS_VAR_BLOCK_FIRST + 128 * ((sizeof(Str_variable_point) + 1) / 2),
//	MODBUS_PRG_BLOCK_LAST     = MODBUS_PRG_BLOCK_FIRST + MAX_PRGS * ((sizeof(Str_program_point) + 1) / 2) - 1,
//		
//	MODBUS_WR_BLOCK_FIRST     = MODBUS_PRG_BLOCK_FIRST + 16 * ((sizeof(Str_program_point) + 1) / 2),
//	MODBUS_WR_BLOCK_LAST      = MODBUS_WR_BLOCK_FIRST + MAX_WR * ((sizeof(Str_weekly_routine_point) + 1) / 2) - 1,
//		
//	MODBUS_AR_BLOCK_FIRST     = MODBUS_WR_BLOCK_FIRST + 8 * ((sizeof(Str_weekly_routine_point) + 1) / 2),
//	MODBUS_AR_BLOCK_LAST      = MODBUS_AR_BLOCK_FIRST + MAX_AR * ((sizeof(Str_annual_routine_point) + 1) / 2) - 1,
//		
//	MODBUS_CODE_BLOCK_FIRST   = MODBUS_AR_BLOCK_FIRST + 4 * ((sizeof(Str_annual_routine_point) + 1) / 2),
//	MODBUS_CODE_BLOCK_LAST    = MODBUS_CODE_BLOCK_FIRST + MAX_PRGS * (CODE_ELEMENT * MAX_CODE / 2) - 1,
//	
//	//16044 - 32043// 1000*16 
//	MODBUS_WR_TIME_FIRST      = MODBUS_CODE_BLOCK_FIRST + 16 * (CODE_ELEMENT * MAX_CODE / 2), 
//	MODBUS_WR_TIME_LAST       = MODBUS_WR_TIME_FIRST + MAX_WR * ((sizeof(Wr_one_day) * MAX_SCHEDULES_PER_WEEK + 1) / 2) - 1,
// 
//	//32044 - 32619  //576
//	MODBUS_AR_TIME_FIRST      = MODBUS_WR_TIME_FIRST + 8 * ((sizeof(Wr_one_day) * MAX_SCHEDULES_PER_WEEK + 1) / 2), 
//	MODBUS_AR_TIME_LAST       = MODBUS_AR_TIME_FIRST + MAX_AR * (AR_DATES_SIZE / 2) - 1,

//	//32620
//	MODBUS_CONTROLLER_BLOCK_FIRST = MODBUS_AR_TIME_FIRST + 4 * (AR_DATES_SIZE / 2),
//	MODBUS_CONTROLLER_BLOCK_LAST  = MODBUS_CONTROLLER_BLOCK_FIRST + MAX_CONS * ((sizeof(Str_controller_point) + 1)/ 2) - 1,
//	
	MODBUS_USER_BLOCK_LAST , 
	
	
	
} 
MODBUS_REGISTER_LIST;

#endif
